### ISSUE TITLE
an exception occured during a WebClient request

### ISSUE THREAD

**Issue by AlaHamad** [ravibpatel/AutoUpdater.NET#141]
I get an error after it downloads the update zip file

![image](https://user-images.githubusercontent.com/24459724/39585069-e849a5ce-4ec1-11e8-89c9-86f5b87491eb.png)

**Comment by ravibpatel** [comment]
@AlaHamad Can you give me URL of your XML file?

**Comment by VLorz** [comment]
Same happends to me when I specify the location for downloading the .zip file using 
`AutoUpdater.DownloadPath = <my_local_path>;` 

The path `<my_local_path>` points to one location where the current user has read/write rights without administrative privileges. I also made sure the full path exists.

When I don't specify the download path the behaviour is different, but also in error. The auto-updater is capable of downloading the .zip file, but an error window pops up showing a **System.UnauthorizedAcessException** with message: 

> Access to the path 'C:\users\my_user_name\AppData\Local\Temp\my_zip_filename.zip' is denied

It works OK when the update file is an executable installer.
Regards

**Comment by ravibpatel** [comment]
@VLorz It works when you specify the path using AutoUpdater.DownloadPath?

**Comment by VLorz** [comment]
@ravibpatel, I've added an update to my previous comment.
Thanks a lot for sharing this work. Best regards.

**Comment by VLorz** [comment]
@ravibpatel, I've traced down the `System.Net.WebException` exception on my system, this time it was rised because the path for the download did not exist. This of course contradicts my first comment.

One possibly appropriated point for ensuring that the download path exits is in file DownloadUpdateDialog.cs, before the call to `_webClient.DownloadFileAsync(uri, _tempFile);`, in line 45. This code did the trick for me:
```C#
if (!Directory.Exists( Path.GetDirectoryName( _tempFile ) ))
                Directory.CreateDirectory( Path.GetDirectoryName( _tempFile ) );
```
Regards
