### ISSUE TITLE
Updater file version problem

### ISSUE THREAD

**Issue by Cormaa** [ravibpatel/AutoUpdater.NET#160]
I have a problem with my updater. The problem is whenever you are restarting software it always needs new version. So the updater does not replace old version with new. So the program always start as 10.0.0 even the updater updates it to 1.0.0.1 correctly

**Comment by nicolharico** [comment]
same problem here, the update process "looks fine", but when rebooting the app, the old version is still installed and prompts for a new version :(

**Comment by nicolharico** [comment]
Did you solve your problem in any way ?

**Comment by ravibpatel** [comment]
@Cormaa @nicolharico Can you post the URL of your XML file?

**Comment by DjordjeMandic** [comment]
@ravibpatel i noticed this bug. if app is deployed as single exe and if current old running exe (doing the update) has different name than new one from zip file or link program will just download that file and extract it and instead of starting new one and deleting old one it will start old one. Example if i have file test.exe and it does update for testnew.exe, test.exe is closed, testnew.exe extracted and test.exe started again instead of testnew.exe. If files are the same name, old file=> test.exe and new one text.exe then old file test.exe will get closed, zip extractor will extract new test.exe by overwriting old one and start that new one again. Did you understand me?
