### ISSUE TITLE
Update windows service using AutoUpdater.NET

### ISSUE THREAD

**Issue by BlueZ-95** [ravibpatel/AutoUpdater.NET#405]
I want to update my application, It runs as a windows service.
The issue is when AutoUpdater.Net tries to download, It shows message box of progress in general but it is not possible in windows service as far as I know.

Due to this my application throws error. Is there any way to disable messagebox when DownloadUpdate(args) method executess?

**Comment by ravibpatel** [comment]
You have to handle check for update event as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#handling-updates-manually) but instead of calling AutoUpdater.DownloadUpdate method you must implement that logic. You can use the code from [here](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/AutoUpdater.NET/DownloadUpdateDialog.cs) to download and execute the installer process.

**Comment by BlueZ-95** [comment]
Thanks, Let me try this. I'll update soon

**Comment by BlueZ-95** [comment]
I've created a new winforms project and linked it with my original project. It works!

**Comment by jeremy-russell-accesso** [comment]
@BlueZ-95 Do you have source that you could share? I to have a windows service app that I need to update via a separate project. Would love to save some time if I could take a peek at what you developed.
