### ISSUE TITLE
Call start without xml file and hide close button in extract form

### ISSUE THREAD

**Issue by mrsiro789** [ravibpatel/AutoUpdater.NET#432]
Hello, i use ParseUpdateInfoEvent and CheckForUpdateEvent to update.
First, with ParseUpdateInfoEvent, i give infomation CurrentVersion,ChangelogURL,DownloadURL,Mandatory. So, i want to call AutoUpdater.Start without xml file path.
Second, i use CheckForUpdateEvent to call update job, i want to hide close button in extract form, because if user click close button while extracting(copy and replace) that maybe incomplete files and app error.

**Comment by zlyxm** [comment]
You can put the .xml in the shared folder and then access
`
AutoUpdater.Start(@"\\Shared file directory\AutoUpdaterTest.xml");
`
I want to know if I can set the FormBorderStyle of ZipExtractor.FormMain to None to hide the close button

**Comment by vbrindus** [comment]
This is something I would also like to be addressed. CurrentVersion and the other update parameters can be extracted from database, which greatly simplifies the creation of different environments like Test, UAT, Prod, etc. In this scenario it's totally reasonable to not have an XML file at all, as everything will be set by the ParseUpdateInfoEvent handler.

A workaround is to provide the URI for any existing file. AutoUpdater will download it but will not parse it itself and will simply pass it to the ParseUpdateInfoEvent handler. The only restriction is that the file has to exist for AutoUpdater to be able to download it, otherwise an exception will be thrown.

Currently calling Start() compiles OK but throws an exception when CheckUpdate() tries to parse AppCastURL in order to download the XML. It should do this only if AppCastURL != null.
