### ISSUE TITLE
Get Update From Shared Network Resources

### ISSUE THREAD

**Issue by NabaviFard-Mahdi** [ravibpatel/AutoUpdater.NET#486]
How to get update from Shared Network Resources?
ex: 
192.168.1.100\Update\AutoUpdater.xml
192.168.1.100\Update\UpdateFile.zip

**Comment by aphestark** [comment]
> How to get update from Shared Network Resources? ex: 192.168.1.100\Update\AutoUpdater.xml 192.168.1.100\Update\UpdateFile.zip

same question, cause not every computer connected to internet

**Comment by NedSeby** [comment]
Hello,

In order to achieve this for my LAN, I've wrote like below:
XML: <url>\\192.168.1.100\Update\UpdateFile.zip</url>
Code: AutoUpdater.Start(@"\\192.168.1.100\Update\AutoUpdater.xml");

It works well for me. I can access the files whether by IP or local server name (eg: \\Server-Name\Update\UpdateFile.zip)

If I got it right, hopefully it will help you.

**Comment by aphestark** [comment]
wow, tks Ned
