### ISSUE TITLE
How delete all exist file and directory in app folder before extract update .zip file into app folder?

### ISSUE THREAD

**Issue by zaiplanet** [ravibpatel/AutoUpdater.NET#506]

**Comment by zaiplanet** [comment]
because i want clear all dump file in app folder first, and then extract .zip update.
Anyone have solution for this?

**Comment by micmartin** [comment]
I'm also interested to use such an option. Maybe by using a "PriorZipExtractEventHandler"?

**Comment by zaiplanet** [comment]
> I'm also interested to use such an option. Maybe by using a "PriorZipExtractEventHandler"?

I know it is possible to do so using 1 installer.  We uninstall before installing with script in NSIS.  but currently there is a folder app extracted by zip file.  I dont known how to delete that folder and run an installer NSIS

**Comment by zaiplanet** [comment]
> I'm also interested to use such an option. Maybe by using a "PriorZipExtractEventHandler"?

Do you have sample code?

**Comment by micmartin** [comment]
After having a closer look at the AutoUpdater code the idea to subscribe to an event handler will not work, because the code is executed within the application to be replaced.
The best option would be to pass a new command line argument to the ZipExtractor to tell it to handle the cleanup.
ZipExtractor is started as a new process and will not block the files to be deleted.

**Comment by ravibpatel** [comment]
This feature is implemented in the latest commit. Please try it from [here](https://ci.appveyor.com/api/buildjobs/5gqj920fhoxy9cc6/artifacts/AutoUpdater.NET-1.7.1.zip) and let me know how it goes.

**Comment by ravibpatel** [comment]
You can turn the feature as shown [here](https://github.com/ravibpatel/AutoUpdater.NET#clear-application-directory-before-extracting-update-file).
